### PR TITLE
Adding sudoers variable to class params

### PR DESCRIPTION
**Pull request by phathocker**
- Update to PR #32

### CODE REVIEW

**Comment by ghoneycutt** [comment]
@phathocker Looks great! A new parameter must also be documented in the README.md and spec tests added. Since sudoers is already a field that was being tested, we just need the following.

* test that setting $sudoers to a non-string will cause a failure
* test that settings $sudoers to a valid string (like 'foo') will ensure that `sudoers:    foo` is in the content of the file.

Here's some examples to get your started
``` ruby
      it 'should fail' do
        expect {
          should contain_class('nsswitch')
        }.to raise_error(Puppet::Error,/invalid type/)
      end
```

``` ruby
it { should contain_file('nsswitch_config_file').with_content(/^sudoers:\s+foo$/) }
```

**Comment by phathocker** [comment]
Thanks @ghoneycutt - I'll get the PR updated.  Do I need to fix the README and spec tests for the other params or did I just overlook them?

```
  $passwd                   = 'USE_DEFAULTS',
  $shadow                   = 'USE_DEFAULTS',
  $group                    = 'USE_DEFAULTS',
  $hosts                    = 'USE_DEFAULTS',
  $automount                = 'USE_DEFAULTS',
  $services                 = 'USE_DEFAULTS',
  $bootparams               = 'USE_DEFAULTS',
  $aliases                  = 'USE_DEFAULTS',
  $publickey                = 'USE_DEFAULTS',
  $netgroup                 = 'USE_DEFAULTS',
```

**Comment by phathocker** [comment]
@ghoneycutt - Any feedback?

**Comment by jyaworski** [comment]
Superceded by #37.

**Comment by ghoneycutt** [comment]
Thanks @phathocker 

This functionality is now present in v1.4.0

**Pull request closed without merging**
