### PR TITLE
Support strict variables in Puppet v4

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Not sure why this is an issue - `Evaluation Error: Unknown variable: '::operatingsystemmajrelease'`

**Comment by Phil-Friderici** [comment]
I have a dark memory that operatingsystemmajrelease is only available when the lsb* packages are installed. Maybe they are not installed in the image used by Travis and it's connected to that ?

**Comment by Phil-Friderici** [comment]
nope, it's not defined in the specs:
https://github.com/ghoneycutt/puppet-module-nsswitch/blob/master/spec/classes/init_spec.rb#L63-L65

**Comment by ghoneycutt** [comment]
Released in v1.5.0

**Pull request merged**
